### PR TITLE
Improve LUTs managements

### PR DESCRIPTION
**Pull request by julien-blanchon**
This PR:
- Switch to `./models` directory for LUTs while keeping compatibility with `./custom_nodes/ComfyUI_essentials/luts`.
- Make subdirectory luts usable and fix https://github.com/cubiq/ComfyUI_essentials/issues/45
- Introduce a `StringToLuts+` helper to still be able to parametrize LUTs

### CODE REVIEW

**Comment by cubiq** [comment]
so this is great but luts are not models, storing them in the /models directory is not technically correct. Probably /input/luts would be more appropriate

**Comment by julien-blanchon** [comment]
I don't 100% agree with this, `embeddings` are not models/checkpoint either but they are by default in the `./models/` directory. And LUTs can be configured as a checkpoint (i.e. a set of parameters). What's important with registers like `models` is to be able to exchange them easily with `extra_model_paths` and by mounting a volume.

I'm not sure it makes sense to put them in `inputs` honestly. I can make a change, but I'm not convince this is the right thing to do

**Comment by masslevel** [comment]
Thanks, @julien-blanchon! I manage a lot of assets including a larger LUT library, so subdirectory support is highly appreciated.

I hope I don't derail the PR with my thoughts. I'll remove the comment if it doesn't fit the topic.

I'm aware that design philosophies can be different for everyone. I just wanted to chime in and list the current patterns I've seen from different ComfyUI custom nodes using user assets.

### Custom nodes using...

- `./models` as a parent directory to store assets / models

- an assets directory inside the node's home directory
  - `./custom-nodes/node/assets`

- a directory in ComfyUI`s root
  - `../ComfyUI/wildcards`

- a config file in the node's home directory to set paths
  - `./custom-nodes/node/config.json`

- a config file in ComfyUI's root to set paths
  - `../ComfyUI/node-config.json`

I personally think `./models` definitely doesn't fit all categories. It's not the best practice but it's already being used as a general assets directory by other custom nodes including `.models/luts`. And the `extra_model_paths.yaml` makes it at least a bit more configurable than other solutions for now.

In general I would prefer a natively implemented ComfyUI user assets directory outside of `./models`, because I think those files shouldn't necessarily be stored in a custom nodes home directory as well to keep the node more maintainable and easier to work with (upgrades etc.). But that hasn't been standardized yet.

There's a `..\ComfyUI\user\` directory but I haven't seen it used for anything else than the native workflow management and UI settings.

**Comment by cubiq** [comment]
I'm reviewing this today, sorry it took so long

**Pull request merged**
